main:
  - name: About
    url: '#about'
    weight: 1
  - name: Blog
    url: /blog/
    weight: 2
#  - name: Docs
#    url: /docs/
#    weight: 3
  - name: Media
    url: '/series/media'
    weight: 4
